name: aircare
publish_to: 'none'
description: Monitoreo y alertas de calidad del aire por Wi-Fi
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.1
  http: ^1.2.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  intl: ^0.20.2
  uuid: ^4.5.1
  connectivity_plus: ^6.0.5
  percent_indicator: ^4.2.3   
  font_awesome_flutter: ^10.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  

flutter:
  uses-material-design: true
